package org.samuel.manuscript;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

/**
 * Writes a technical documentation scaffold and compiles it via pdflatex.
 */
public class ManuscriptGenerator {

    public void generate(Path manuscriptDir, Map<String, Object> stats) throws IOException, InterruptedException {
        Files.createDirectories(manuscriptDir);
        write(manuscriptDir.resolve("introduction.tex"), """
                \\section{Introduction}
                SAMUeL is a QuPath extension that integrates Segment Anything (SAM) for annotation-prompted segmentation of microscopy images.
                """);
        write(manuscriptDir.resolve("methods.tex"), """
                \\section{Architecture}
                The extension consists of:
                \\begin{itemize}
                \\item Java QuPath extension with GUI
                \\item Python FastAPI backend for SAM inference
                \\item Tile-based processing for large images
                \\item Prompt conversion from QuPath annotations
                \\end{itemize}
                """);
        write(manuscriptDir.resolve("results.tex"), """
                \\section{Usage Statistics}
                Tiles processed: %d\\\\
                Objects generated: %d\\\\
                """.formatted(stats.getOrDefault("tiles", 0), stats.getOrDefault("objects", 0)));
        write(manuscriptDir.resolve("discussion.tex"), """
                \\section{Technical Details}
                SAM models: vit\\_h, vit\\_l, vit\\_b\\\\
                Tiling strategy: Overlapping tiles with configurable size\\\\
                Output formats: QuPath detections or annotations
                """);
        write(manuscriptDir.resolve("supplementary.tex"), """
                \\section*{Configuration}
                Backend URL: http://127.0.0.1:8000\\\\
                Python dependencies: FastAPI, PyTorch, segment-anything\\\\
                Java dependencies: QuPath GUI, Jackson, ControlsFX
                """);
        write(manuscriptDir.resolve("references.bib"), """
                @article{kirillov2023segment,
                  title={Segment Anything},
                  author={Kirillov, Alexander and others},
                  journal={arXiv preprint arXiv:2304.02643},
                  year={2023}
                }
                @software{qupath,
                  title={QuPath: Open source software for digital pathology image analysis},
                  author={Bankhead, Peter and others},
                  year={2017}
                }
                """);
        write(manuscriptDir.resolve("manuscript.tex"), """
                \\documentclass{article}
                \\usepackage[margin=1in]{geometry}
                \\usepackage{graphicx}
                \\begin{document}
                \\title{SAMUeL Technical Documentation}
                \\author{Generated by SAMUeL extension}
                \\maketitle
                \\input{introduction.tex}
                \\input{methods.tex}
                \\input{results.tex}
                \\input{discussion.tex}
                \\input{supplementary.tex}
                \\bibliographystyle{plain}
                \\bibliography{references}
                \\end{document}
                """);
        ProcessBuilder pb = new ProcessBuilder("pdflatex", "manuscript.tex");
        pb.directory(manuscriptDir.toFile());
        pb.redirectErrorStream(true);
        Process p = pb.start();
        p.waitFor();
    }

    private void write(Path path, String content) throws IOException {
        Files.writeString(path, content);
    }
}
